title: Mansoor's Personal Blog
author: Mansoor Poonawala
email: mpoonawala@ebnet.org
description: > # this means to ignore newlines until "baseurl:"
  A 17 year old kid who wants to travel the world with big dreams :)

# social links
twitter_username: MansoorPoona1 # DO NOT include the @ character, or else the build will fail!
github_username:  MansoorPoona1 # DO NOT include the @ character, or else the build will fail!
instagram_username: mansoor_poona

show_excerpts: true # set to false to remove excerpts on the homepage
theme: minima
